language: erlang
matrix:
  include:
    - os: linux
      otp_release: 19.0
    - os: linux
      otp_release: 19.1
    - os: linux
      otp_release: 19.2
    - os: linux
      otp_release: 19.3
    - os: linux
      otp_release: 20.0
    - os: linux
      otp_release: 20.1